// One versioned text shared by the app and registration endpoint.
export const CONDITIONS_VERSION = '2026-10-08-uso-v1';
export const platformConditions = [
  { title: 'Uso interno y cifras referenciales', text: 'Esta herramienta permite consultar indicadores comerciales y noticias internas. Los valores dependen de las planillas publicadas y su fecha de actualización, pueden variar por emisión, anulaciones, correcciones y cierres. No sustituyen liquidaciones, documentos oficiales ni decisiones de la empresa. No determinan por sí solos premios, remuneraciones o sanciones.' },
  { title: 'Datos utilizados y finalidad', text: 'Para identificar tu cuenta y mostrar tu avance se usan RUT, nombre, rol, equipo, estado de habilitación, fechas laborales y métricas agregadas de ventas, producción, mora, Senior y categorización. Si se carga tu cumpleaños se usa para el saludo. No se deben cargar nombres, RUT, teléfonos, direcciones ni antecedentes de clientes. El estado de acceso no debe incluir diagnósticos ni causas de licencias.' },
  { title: 'Acceso según cargo', text: 'Cada ejecutivo consulta su detalle. Coordinadores y jefaturas acceden a sus equipos y la dirección al canal autorizado. Los rankings muestran nombres y resultados comerciales comparables a usuarios habilitados. Administración gestiona datos y cuentas; Audiovisual edita exclusivamente noticias. No compartas contraseñas ni redistribuyas datos, capturas o fotografías fuera de las personas autorizadas.' },
  { title: 'Noticias y fotografías', text: 'Quien publique debe contar con autorización para las imágenes y textos, respetar derechos de imagen y no incluir clientes ni documentos con datos personales. La aceptación de estas condiciones no autoriza publicar tu fotografía: esa autorización se gestiona por separado. Puedes solicitar revisión o retiro de contenido al administrador.' },
  { title: 'Consultas, correcciones y derechos', text: 'Ante diferencias o dudas solicita revisión al administrador de la plataforma o a tu jefatura por los canales internos que ya conoces. Puedes solicitar información sobre tus datos, corrección y las demás acciones que correspondan conforme a la legislación aplicable. Estas condiciones no limitan tus derechos ni reemplazan los procedimientos oficiales.' },
  { title: 'Servicios y seguridad', text: 'La herramienta utiliza Supabase para autenticación, almacenamiento y base de datos, y Expo para distribuir actualizaciones. Se aplican controles de acceso y medidas de seguridad; ningún sistema garantiza riesgo cero. Comunica inmediatamente cualquier acceso indebido o filtración al administrador. No publiques claves, contraseñas ni archivos completos con datos de clientes.' },
  { title: 'Información legal pendiente de aprobación', text: 'Este aviso y las condiciones de uso son una versión operativa pendiente de revisión y autorización institucional. No se declara una razón social ni un contacto corporativo sin su autorización. Antes de adopción institucional deben identificarse el responsable del tratamiento, su contacto, la base jurídica, los plazos de conservación, encargados y transferencias de datos, y el procedimiento de derechos e incidentes. Aceptar estas condiciones no equivale a esa aprobación, no es una certificación legal y no constituye una autorización ilimitada para tratar datos.' },
] as const;
