begin;

alter table public.profiles drop constraint profiles_role_check;
alter table public.profiles add constraint profiles_role_check
 check(role in ('seller','coordinator','sales_manager','admin','audiovisual'));
alter table public.profiles add column employment_status text not null default 'active'
 check(employment_status in ('active','detached','medical_leave','vacation'));
update public.profiles p set employment_status=w.status from public.commercial_workers w
 where w.rut=lower(regexp_replace(p.rut,'[^0-9kK]','','g')) and p.role not in ('admin','audiovisual');

create or replace function private.can_edit_news() returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles p where p.id=(select auth.uid())
 and p.active and p.employment_status='active' and p.role in ('admin','audiovisual'));
$$;
create or replace function private.can_access_commercial() returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles p where p.id=(select auth.uid())
 and p.active and p.employment_status='active' and p.role in ('seller','coordinator','sales_manager','admin'));
$$;
revoke all on function private.can_edit_news(), private.can_access_commercial() from public, anon;
grant execute on function private.can_edit_news(), private.can_access_commercial() to authenticated;

create or replace function private.sheet_access() returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles p left join public.commercial_workers w
 on w.rut=lower(regexp_replace(p.rut,'[^0-9kK]','','g'))
 where p.id=(select auth.uid()) and p.active and p.employment_status='active'
 and (p.role='admin' or (p.role in ('seller','coordinator','sales_manager') and w.active and w.status='active')));
$$;
create or replace function private.sheet_worker_allowed(target_id text) returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles p
 left join public.commercial_workers me on me.rut=lower(regexp_replace(p.rut,'[^0-9kK]','','g'))
 join public.commercial_workers target on target.id=target_id
 where p.id=(select auth.uid()) and p.active and p.employment_status='active'
 and (p.role='admin' or (p.role in ('seller','coordinator','sales_manager') and me.active and me.status='active' and target.active and target.status='active'
 and (target.id=me.id or (me.role='coordinator' and target.coordinator_id=me.id)
 or (me.role='sales_manager' and target.manager_id=me.id)))));
$$;

-- Restrictive guards also cover older tables with broad authenticated policies.
do $$ declare t text; begin
 foreach t in array array['teams','competitions','ranking_entries','executive_metrics','goals','sales','delinquency_records','upload_batches','metric_snapshots','category_tiers','senior_bonus_rules','commercial_workers','sheet_uploads','sheet_metrics','current_sheet_uploads'] loop
  execute format('create policy commercial_roles_only on public.%I as restrictive for all to authenticated using ((select private.can_access_commercial())) with check ((select private.can_access_commercial()))',t);
 end loop;
end $$;
create policy profiles_news_only_guard on public.profiles as restrictive for select to authenticated
 using(id=(select auth.uid()) or (select private.can_access_commercial()));

create table public.news_sections (
 id bigint generated by default as identity primary key,
 news_article_id bigint not null references public.news_articles(id),
 title text not null check(length(trim(title)) between 1 and 180),
 description text not null check(length(trim(description)) between 1 and 10000),
 sort_order bigint not null default 0,
 active boolean not null default true,
 created_at timestamptz not null default now(),
 unique(id,news_article_id)
);
create index news_sections_article_idx on public.news_sections(news_article_id);
alter table public.gallery_images add column news_section_id bigint;
alter table public.gallery_images add constraint gallery_section_article_fk
 foreign key(news_section_id,news_article_id) references public.news_sections(id,news_article_id);
alter table public.gallery_images add constraint gallery_section_has_article
 check(news_section_id is null or news_article_id is not null);
create index gallery_images_section_idx on public.gallery_images(news_section_id);
alter table public.news_sections enable row level security;
grant select,insert,update,delete on public.news_sections to authenticated;
grant usage,select on sequence public.news_sections_id_seq to authenticated;
create policy news_sections_read on public.news_sections for select to authenticated
 using(active or (select private.can_edit_news()));
create policy news_sections_edit on public.news_sections for all to authenticated
 using((select private.can_edit_news())) with check((select private.can_edit_news()));

alter policy news_articles_admin_insert on public.news_articles with check((select private.can_edit_news()));
alter policy news_articles_admin_update on public.news_articles using((select private.can_edit_news())) with check((select private.can_edit_news()));
alter policy news_articles_admin_delete on public.news_articles using((select private.can_edit_news()));
alter policy gallery_images_admin_insert on public.gallery_images with check((select private.can_edit_news()));
alter policy gallery_images_admin_update on public.gallery_images using((select private.can_edit_news())) with check((select private.can_edit_news()));
alter policy gallery_images_admin_delete on public.gallery_images using((select private.can_edit_news()));
create policy news_media_editors_read on storage.objects for select to authenticated
 using(bucket_id='news-media' and (select private.can_edit_news()));
alter policy news_media_admin_insert on storage.objects with check(bucket_id='news-media' and (select private.can_edit_news()));
alter policy news_media_admin_update on storage.objects using(bucket_id='news-media' and (select private.can_edit_news())) with check(bucket_id='news-media' and (select private.can_edit_news()));
alter policy news_media_admin_delete on storage.objects using(bucket_id='news-media' and (select private.can_edit_news()));
alter publication supabase_realtime add table public.news_sections;

create or replace function public.publish_individual_sheet(p_upload jsonb,p_records jsonb) returns uuid
language plpgsql set search_path='' as $$
declare new_id uuid;n integer;
begin
 if not coalesce(private.is_admin(),false) then raise exception 'No autorizado';end if;
 if jsonb_typeof(p_records) is distinct from 'array' then raise exception 'Filas inválidas';end if;
 if jsonb_array_length(p_records) not between 1 and 10000 then raise exception 'Filas inválidas';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('sheet:'||(p_upload->>'source')));
 if exists(select 1 from jsonb_array_elements(p_records)x where jsonb_typeof(x->'metrics') is distinct from 'object' or length((x->'metrics')::text)>10000) then raise exception 'Métricas inválidas';end if;
 if exists(select 1 from jsonb_array_elements(p_records)x,jsonb_object_keys(x->'metrics')k where k not in
 ('smad','smadRemaining','uf','prize','level','remaining','rest','ssff','tenureMonths','cancellationUf','potentialLevel','emittedSmad','emittedLevel',
 'businesses','productivity','headcount','teamProduction','employmentStatus','lastSaleDate','daysWithoutSale','daysWithoutSaleText',
 'debtSales','debtUf','debtInstallments','debtUf08','debtSales08','risk','position','emittedUf','notEmittedUf','totalUf')) then raise exception 'Columna no permitida';end if;
 insert into public.sheet_uploads(source,filename,sheet_name,label,period_start,period_end,senior_status,rules,published_by)
 values(p_upload->>'source',p_upload->>'filename',p_upload->>'sheet_name',p_upload->>'label',(p_upload->>'period_start')::date,(p_upload->>'period_end')::date,p_upload->>'senior_status',coalesce(p_upload->'rules','[]'::jsonb),(select auth.uid())) returning id into new_id;
 insert into public.sheet_metrics(upload_id,worker_id,metrics,source_row)
 select new_id,x->>'worker_id',x->'metrics',(x->>'source_row')::integer from jsonb_array_elements(p_records)x;
 get diagnostics n=row_count;
 if n<>jsonb_array_length(p_records) then raise exception 'Carga incompleta';end if;
 insert into public.current_sheet_uploads(source,upload_id)values(p_upload->>'source',new_id) on conflict(source)do update set upload_id=excluded.upload_id;
 return new_id;
end $$;

create or replace function private.sheet_ranking(p_period text,p_target text) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare me public.commercial_workers;profile_role text;target_id text;result jsonb;
begin
 if not private.sheet_access() then raise exception 'Error al comunicar con el servidor';end if;
 select p.role,w.id into profile_role,target_id from public.profiles p left join public.commercial_workers w
 on w.rut=lower(regexp_replace(p.rut,'[^0-9kK]','','g')) where p.id=(select auth.uid());
 if p_target is not null then
  if profile_role<>'admin' and p_target is distinct from target_id then raise exception 'No autorizado';end if;
  target_id=p_target;
 end if;
 select * into me from public.commercial_workers where id=target_id and active and status='active';
 if me.id is null and profile_role<>'admin' then raise exception 'Error al comunicar con el servidor';end if;
 if p_period is null or p_period not in ('annual','monthly') then raise exception 'Período inválido';end if;
 -- Never present the old emitted-only upload as a total ranking.
 if not exists(select 1 from public.current_sheet_uploads c join public.sheet_metrics m on m.upload_id=c.upload_id
 where c.source='ranking_'||p_period and m.metrics ? 'totalUf') then return '[]'::jsonb;end if;
 with values_by_seller as (
  select w.id,w.name,w.coordinator_id,w.manager_id,coalesce((m.metrics->>'totalUf')::numeric,0)as uf,
  coalesce((m.metrics->>'emittedUf')::numeric,0)as emitted
  from public.commercial_workers w
  left join public.current_sheet_uploads c on c.source='ranking_'||p_period
  left join public.sheet_metrics m on m.upload_id=c.upload_id and m.worker_id=w.id
  where w.role='seller' and w.active and w.status='active'
 ),entities as (
  select id,name,uf,emitted from values_by_seller where coalesce(me.role,'seller')='seller'
  union all
  select w.id,w.name,coalesce(sum(s.uf),0),coalesce(sum(s.emitted),0)from public.commercial_workers w
  left join values_by_seller s on s.coordinator_id=w.id
  where w.active and w.status='active' and w.role='coordinator'
  and (me.role='coordinator' or (me.role='sales_manager' and w.manager_id=me.id))group by w.id,w.name
 ),ranked as(select *,rank()over(order by uf desc)as position from entities)
 select coalesce(jsonb_agg(jsonb_build_object('userId',id,'name',name,'value',uf,'emittedValue',emitted,
 'notEmittedValue',greatest(uf-emitted,0),'position',position,'teamId',id,'avatar','','isCurrentUser',id=target_id)
 order by position,name),'[]'::jsonb)into result from ranked;
 return result;
end $$;

commit;
